# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TraiNminaTor
                                 A QGIS plugin
 test de nouveau plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-25
        copyright            : (C) 2021 by World Compagny
        email                : yann.le-borgne@ign.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TraiNminaTor class from file TraiNminaTor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TraiNminaTor import TraiNminaTor
    return TraiNminaTor(iface)
